# Generated by Django 3.2.25 on 2024-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
